DataDog/the-monitor

- openstack/devstack/deploy_droplet.py
- openstack/devstack/stack_setup.sh
scripts for deploying DevStack to Digital Ocean
> devstack scripts

- varnish/how_to_monitor_varnish.md
Based on https://www.varnish-cache.org/docs/4.1/reference/varnish-counters.html
> Correct varnish `thread` state description

- docker/3_how_to_collect_docker_metrics.md
> [docker] Add metric paths for CoreOS pseudo-files

- haproxy/how_to_collect_haproxy_metrics.md
> Update HAProxy config to enable stats for latest versions

- docker/3_how_to_collect_docker_metrics.md
Part 4 is no longer coming soon.
> Link to part 4 of docker metric blog posts

- openstack/host_aggregates.md
- openstack/openstack_nova_monitoring.md
- translations/ja-jp/openstack/host_aggregates.md
- translations/ja-jp/openstack/openstack_nova_monitoring.md
> replace references to old distro

- google-compute-engine/how-to-collect-gce-metrics.md
- google-compute-engine/monitor-google-compute-engine-with-datadog.md
- google-compute-engine/monitoring-google-compute-engine-performance.md
Markdown release of the [Google Compute Engine monitoring series](https://www.datadoghq.com/blog/monitoring-google-compute-engine-performance/#toc-acknowledgment).
> push GCE longform

- kubernetes/monitoring-kubernetes-with-datadog.md
> Corrects capitalization in k8s manifest

- redis/how_to_monitor_redis_performance.md
> Switch from spans to divs for math

- activemq/activemq-architecture-and-metrics.md
- activemq/collecting-activemq-metrics.md
- activemq/monitoring-activemq-with-datadog.md
> Merge ActiveMQ series into master

- pivotal-cloud-foundry/collecting-pcf-logs.md
- pivotal-cloud-foundry/pcf-monitoring-with-datadog.md
- pivotal-cloud-foundry/pivotal-cloud-foundry-architecture.md
- pivotal-cloud-foundry/pivotal-cloud-foundry-metrics.md
Remove front matter yaml from the PCF posts.
> Remove front matter

- tomcat/tomcat-architecture-and-performance.md
Weird formatting issue with tables
> tweaking tables

- rds-mysql/how_to_collect_rds_mysql_metrics.md
Part of this task: https://trello.com/c/7ojvxeW1
Updated this post on the blog: https://www.datadoghq.com/blog/how-to-collect-rds-mysql-metrics/#using-the-command-line-interface
And now pushing the same updates to this repo.
> Updating mentions of CLI

- rds-mysql/how_to_collect_rds_mysql_metrics.md
Fixes formatting error in #99 
Part of this task: https://trello.com/c/7ojvxeW1
Updated this post on the blog: https://www.datadoghq.com/blog/how-to-collect-rds-mysql-metrics/#using-the-command-line-interface
And now pushing the same updates to this repo.
> David.lentz/update mentions of cloudwatch cli

- tomcat/analyzing-tomcat-logs-and-metrics-with-datadog.md
- tomcat/tomcat-architecture-and-performance.md
For https://trello.com/c/UbObiocK/1441-update-apm-tomcat-monitoring-tools
> Update Tomcat P1 & P3

- nginx/how_to_monitor_nginx_with_datadog.md
This updates this post in The Monitor to match the version that's in corp-hugo.
> Update How to monitor NGINX to match the corp-hugo version

- kafka/collecting-kafka-performance-metrics.md
- kafka/monitor-kafka-with-datadog.md
- kafka/monitoring-kafka-performance-metrics.md
We published updates to the Kakfa longform earlier this month. This brings `the-monitor` up to date.
> Update to match corp-hugo

- efs/amazon-efs-metrics.md
- efs/amazon-efs-monitoring-datadog.md
- efs/amazon-efs-monitoring-tools.md
Add to this repo the EFS monitoring guide series we published on the blog: https://www.datadoghq.com/blog/amazon-efs-metrics/
> Add EFS series

- activemq/activemq-architecture-and-metrics.md
- activemq/collecting-activemq-metrics.md
- activemq/monitoring-activemq-with-datadog.md
Updates the ActiveMQ series to included information about Artemis.
> David.lentz/activemq update 1

- haproxy/how_to_collect_haproxy_metrics.md
Fixes #128
No preview site available, but you can see the rendered markdown [here](https://github.com/DataDog/the-monitor/blob/b83976674c393f8d878f862e94e54e098e35bcb6/haproxy/how_to_collect_haproxy_metrics.md).
> Update sample code
